name: employe_details
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  uuid: ^3.0.7
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  file_picker: ^5.2.5

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  build_runner:
  hive_generator:

flutter: 
  uses-material-design: true

